apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-web
  name: hello-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-web
    spec:
      containers:
        - image: gcr.io/gke-deploy3/github.com/dorbin/kubernetes-engine-samples
          imagePullPolicy: IfNotPresent
          name: hello-app

